micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bd_cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234567
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update